### ISSUE TITLE
Folder encryption

### ISSUE THREAD

**Issue by chrisidefix** [chrissimpkins/crypto#1]
Would you consider including a better option to encrypt / decrypt folders? I assume making a tar/rar archive (uncompressed) before encryption would be one option, but I was wondering if there is a faster / better solution you would consider?

**Comment by chrissimpkins** [comment]
So, feature request for automated tar.gz or .zip archive creation prior to encryption of the entire archive?  

I haven't built that in because archive creation is widely available but it is simple to do and Python supports it across platforms (including Windows).  What OS are you on?

**Comment by chrisidefix** [comment]
Yes, I suppose you can call this a feature request. I'm on Mac OS X mostly. Just testing a very simple script to tar/untar directories right now (using tarfile) - it's as easy as you said and probably doesn't need to be integrated into your code.

It might make more sense to do this as a pre-processing step, where one might also want to create a split archive before encryption, but I did see you giving examples for directory encryption/decryption with confused me a little when it didn't work as expected. After looking at your documentation again, I realised that - by design - only files inside top level directory are encrypted - for an 'easy-to-use' approach this might not be ideal?
