### ISSUE TITLE
installed but not getting import

### ISSUE THREAD

**Issue by saikiran994** [chrissimpkins/crypto#22]
i installed crypto lib but its not working.......
screenshot has clear information. how to solve this issue?  
need this lib urgently
![Screenshot (2)](https://user-images.githubusercontent.com/37449869/67669100-41c02480-f997-11e9-8b6c-31bf915ffc01.png)

**Comment by chrissimpkins** [comment]
Perhaps you have the wrong library?  There is no `Crypto.Cipher` object in this project.

The `crypto` module is available (note lower case) but it only contains the `main()` function for the executable released here.

**Comment by saikiran994** [comment]
module is avilable but its not importing the module..... i installed it but still no use.....now trying in windows but getting same issue
![Screenshot (3)](https://user-images.githubusercontent.com/37449869/67769982-760d1100-fa7b-11e9-9e1e-332f05c243a3.png)
![Screenshot (4)](https://user-images.githubusercontent.com/37449869/67769984-76a5a780-fa7b-11e9-853d-d7b61302d076.png)

**Comment by chrissimpkins** [comment]
Sorry. I mean the cap `Crypto` module is not part of this project.  I think you that source may rely on a different library/package.

**Comment by VictorASF** [comment]
Sup man, the library are you looking for is pycryptodome

**Comment by chrissimpkins** [comment]
tyvm @VictorASF
