### ISSUE TITLE
v1.4.0

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/crypto#5]
## Source
- [x] tar file generator switch for user directories (Issue #3)
- [x] automated tar file decryption for files generated with #3 

## Docs
- [x] add new `--tar` switch
- [x] add new `--nountar` switch
- [x] update README (Github)
- [x] update README.rst (PyPI)

**Comment by chrisidefix** [comment]
I think it's worth mentioning that the dependencies inside setup.py may also have to be updated, but I am not too familiar with what exactly should go in there - would the "tarfile" package need to be referenced?

**Comment by chrissimpkins** [comment]
Python builtin's don't need to be referenced in the `setup.py` file. Only external (i.e. non-Python builtin) dependencies.  For instance if you are using a package/library from [PyPI](https://pypi.python.org/pypi) in your project, you would include the name of the package in the install_requires field (https://github.com/chrissimpkins/crypto/blob/master/setup.py#L47).  This definition is formatted as a Python list.  I am installing the application in a virtual env and testing with updates to the source so we will pick up on dependency issues before it is released.  Worry about it only to the degree that it will make you a better developer to understand your install/deployment files.  It's going to be solid before we release to users.   That falls well within my bounds as the project maintainer. 

Keep hammering away at your code!  Looks great.

**Comment by chrisidefix** [comment]
pull requests for the source additions are in place. Feel free to have a look at them, whenever you get around to it. I also implemented a --passcode input option and will write a quick feature request for that one, in case you also want to include that into v1.4.0.

**Comment by chrissimpkins** [comment]
released
